# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lf5pPIxYqpPgsP8W9tSGPxaOS0RRv_JE
"""

import numpy as np
# import pandas as pd
import csv

def readCsv(filename):
  with open(filename, "r") as file:
    csv_reader = csv.reader(file)
    header = next(csv_reader)
    data = [] #isinya berupa list data
    for row in csv_reader:
      data.append(row)
    
  return header, data

def tampilkanData(data):
  for row in data:
    print(row)

def modifikasiData(data, missing_value):
  for row in data:
    for i, value in enumerate(row):
      if value in missing_value:
        row[i] = None
        
  return data

def checkNull(data):
  null_count = 0
  for row in data:
    for value in row:
      if value is None:
        null_count += 1
  if null_count == 0:
    print("Tidak ada nilai NULL di dalam data")
  else:
    print(f"Total nilai null : {null_count}")

def checkColumnNull(data, column_number, header):
  null_count = 0
  for row in data:
    if row[column_number - 1] is None:
      null_count += 1
    print(f'Total nilai NULL pada column : {header[column_number - 1]}: {null_count}')

def main():
  filename = input("Masukkan file input")
  header, data = readCsv(filename)
  while True:
    print("SILAHKAN PILIH MENU DI BAWAH INI\n")
    print("A, tampilkan data asli")
    print("B, tampilkan data modifikasi")
    print("C, cek null keseluruhan")
    print("D, menghitung jumlah total null")
    print("E, membaca perkolom sesuai inputan user")
    print("Q, Keluar")

    choice = input("Masukkan pilihan : ")


    if (choice == "A"):
      tampilkanData(data)
    elif (choice == "B"):
      modified_data = modifikasiData(data, ["--", "?"])
    elif (choice == "C"):
      checkNull(data)
    elif (choice == "D"):
      null_count = sum(row.count[None] for row in data)
      print(f"Total nilai NULL pada column : {null_count}")
    elif (choice == "E"):
      print("Kolom yang tersedia : ")
      for i, col in enumerate(header):
        print(f"{i+1}.{col}")
      while True :
        column_choice = input("Pilih column yang akan dicek : ")
        try :
          column_number = int(column_choice)
          if column_number >= 1 and column_number <= len(header):
            break
          else :
            print("Nomor tidak valid")
        except ValueError:
          print("Input tidak aktif")
    elif(choice == "Q"):
        break
      
    else:
        print("Menu tidak ada, silahkan coba lagi")
      
if __name__ == '__main__':
    main()